companies = [
    "AKBLTFC6 - Askari Bank(TFC6)",
    "AKBLTFC7 - Askari Bank(TFC7)",
    "BAFLTFC6 - Bank Al-Falah(TFC6",
    "BAFLTFC8 - Bank Alfalah(TFC8)",
    "BAHLTFC10 - BANK AL HABIB LTD. (10TH ISSUE)",
    "BAHLTFC9 - Bank Al-Habib(TFC9",
    "BIPLSC - Bank IslamiSC",
    "BIPLSC2 - BankIslami Pakistan Ltd",
    "BOPTFC2 - Bank Of Punjab(TFC",
    "HBLTFC2 - Habib Bank(TFC2)",
    "HBLTFC3 - Habib Bank (TFC3)",
    "HUBPHLSC - Hub Power Holding",
    "JSBLTFC2 - JS Bank Ltd(TFC2)",
    "JSBLTFC3 - JS Bank(TFC)",
    "JSBLTFC4 - JS BANK (TFC)",
    "KELSC5 - K-Electric(Sukuk5)",
    "KELSC6 - K-Electric LtdSC6",
    "KFGB1 - Kashf Foundation Gender Bond",
    "MUGHALSC - Mughal Steel Sukuk",
    "P01GIS031225 - 1 Year GIS Discounted Mat.03-12-25",
    "P01GIS061125 - 1 Year GIS Disounted Mat.06-11-25",
    "P01GIS080425 - 1 Year GIS Discounted Mat.08-04-25",
    "P01GIS090525 - 1 Year GIS Discounted Mat.09-05-25",
    "P01GIS140325 - 1 Year GIS Discounted Mat. 14-03-25",
    "P01GIS150825 - 1 Year GIS- Discounted-Mat 15-08-25",
    "P01GIS170925 - 1 Year GIS Discounted - Mat. 17-09-25",
    "P01GIS190225 - 1 Year Ijarah Sukuk Mat 19-feb-25",
    "P01GIS201025 - 1 Year GIS Discounted Mat.20-10-25",
    "P01GIS220125 - 1 Yr GIS Discounted Mat. 22-Jan-25",
    "P01GIS230525 - 1 Year GIS Discounted Mat.23-05-25",
    "P01GIS250425 - 1 Year GIS Discounted Mat.25-04-25",
    "P01GIS250725 - 1 Year GIS Discounted Mat.25-07-25",
    "P01GIS270625 - 1 Year GIS Discounted Mat.27-06-25",
    "P01GIS280325 - 1 Year GIS Discounted Mat. 28-03-25",
    "P02PFL060425 - P02PFL060425",
    "P02PFL090225 - P02PFL090225",
    "P02PFL210925 - P02PFL210925",
    "P03FRR100527 - 3 Year Fixed Rental Rate - Mat.10-May-27",
    "P03FRR180927 - 3 Year Fixed Rental Rate Mat. 18-09-27",
    "P03FRR211027 - 3 Year Fixed Rental Rate Mat.21-10-27",
    "P03FRR240127 - 3 Year Fixed Rental Rate-Mat. 24-Jan-27",
    "P03FRR280627 - 3 Year Fixed Rental Rate - Mat.28-Jun-27",
    "P03PFL090226 - P03PFL090226",
    "P03PFL191026 - P03PFL191026",
    "P03PFL210926 - P03PFL210926",
    "P03PIB040825 - P03PIB040825",
    "P03PIB050824 - P03PIB050824",
    "P03VRR100527 - 3 Yr Variable Rental Rate -Mat.10-May-27",
    "P03VRR180927 - 3 Yr Variable Rental Rate Mat 18-09-27",
    "P03VRR211027 - 3 Yr Variable Rental Rate -Mat.21-Oct-27",
    "P03VRR240127 - 3 Yr Variable Rental Rate -Mat.24-Jan-27",
    "P03VRR280627 - 3 Yr Variable Rental Rate -Mat.28-Jun-27",
    "P05FRR100529 - 5 Yr Fixed Rental Rate -Mat. 10-May-29",
    "P05FRR180929 - 5 Yr Fixed Rental Rate Mat. 18-09-29",
    "P05FRR211029 - 5 Yr Fixed Rental Rate - Mat. 21-Oct-29",
    "P05FRR240129 - 5 Yr Fixed Rental Rate -Mat. 24-Jan-29",
    "P05FRR280629 - 5 Yr Fixed Rental Rate - Mat.28-Jun-29",
    "P05GIS091225 - P05GIS091225",
    "P05GIS290725 - P05GIS290725",
    "P05GIS300425 - P05GIS300425",
    "P05PFL060428 - P05PFL060428",
    "P05PFL161127 - P05PFL161127",
    "P05PFL180625 - P05PFL180625",
    "P05PFL191028 - P05PFL191028",
    "P05PFL210928 - P05PFL210928",
    "P05PIB131027 - P05PIB131027",
    "P05PIB151025 - P05PIB151025",
    "P05PIB190924 - P05PIB190924",
    "P05PIB290427 - P05PIB290427",
    "P05VRR100529 - 5 Yr Variable Rental Rate -Mat.10-May-29",
    "P05VRR180929 - 5 Yr Variable Rental Rate - Mat.18-09-29",
    "P05VRR211029 - 5 Yr Variable Rental Rate -Mat.21-Oct-29",
    "P05VRR240129 - 5 Yr Variable Rental Rate -Mat.24-Jan-29",
    "P05VRR280629 - 5 Yr Variable Rental Rate -Mat.28-06-29",
    "P10FRR180934 - 10 Year Fixed Rental Rate Mat. 18-09-34",
    "P10FRR211034 - 10 Year Fixed Rental Rate Mat. 21-10-34",
    "P10PFL220829 - P10PFL220829",
    "P10PIB101230 - P10PIB101230",
    "P10PIB120728 - P10PIB120728",
    "P10PIB190929 - P10PIB190929",
    "P10VRR180934 - 10 Yr Variable Rental Rate -Mat.18-09-34",
    "P10VRR211034 - 10 Yr Variable Rental Rate -Mat.21-10-34",
    "PESC1 - Pak Energy(Sukuk)",
    "PESC2 - Pak Energy(SukukII",
    "PK03TB060225 - PK03TB060225",
    "PK03TB060325 - PK03TB060325",
    "PK03TB090125 - PK03TB090125",
    "PK03TB200225 - PK03TB200225",
    "PK03TB200325 - PK03TB200325",
    "PK03TB230125 - PK03TB230125",
    "PK03TB281124 - PK03TB281124",
    "PK06TB020525 - PK06TB020525",
    "PK06TB030425 - PK06TB030425",
    "PK06TB060225 - PK06TB060225",
    "PK06TB060325 - PK06TB060325",
    "PK06TB090125 - PK06TB090125",
    "PK06TB120625 - PK06TB120625",
    "PK06TB121224 - PK06TB121224",
    "PK06TB150525 - PK06TB150525",
    "PK06TB170425 - PK06TB170425",
    "PK06TB200225 - PK06TB200225",
    "PK06TB230125 - PK06TB230125",
    "PK06TB260625 - PK06TB260625",
    "PK06TB261224 - PK06TB261224",
    "PK06TB281124 - PK06TB281124",
    "PK06TB290525 - PK06TB290525",
    "PK12TB020525 - PK12TB020525",
    "PK12TB021025 - PK12TB021025",
    "PK12TB040925 - PK12TB040925",
    "PK12TB060225 - PK12TB060225",
    "PK12TB060325 - PK12TB060325",
    "PK12TB070825 - PK12TB070825",
    "PK12TB090125 - PK12TB090125",
    "PK12TB100725 - PK12TB100725",
    "PK12TB111225 - PK12TB111225",
    "PK12TB120625 - PK12TB120625",
    "PK12TB121224 - PK12TB121224",
    "PK12TB131125 - PK12TB131125",
    "PK12TB150525 - PK12TB150525",
    "PK12TB161025 - PK12TB161025",
    "PK12TB170425 - PK12TB170425",
    "PK12TB200225 - PK12TB200225",
    "PK12TB200325 - PK12TB200325",
    "PK12TB210825 - PK12TB210825",
    "PK12TB230125 - PK12TB230125",
    "PK12TB240725 - PK12TB240725",
    "PK12TB260625 - PK12TB260625",
    "PK12TB261224 - PK12TB261224",
    "PK12TB261225 - PK12TB261225",
    "PK12TB271125 - PK12TB271125",
    "PK12TB281124 - PK12TB281124",
    "PK12TB290525 - PK12TB290525",
    "PK12TB301025 - PK12TB301025",
    "SBLTFC - Samba Bank Ltd.(TF",
    "SNBLTFC3 - Soneri Bank(TFC3)",
    "SNBLTFC4 - SONERI BANK LIMITED (4TH ISSUE)",
    "TPLPTFC2 - TPL Properties Limited",
    "TPLSC - TPL Corp Ltd.(SC)",
    "TPLTFC3 - TPLCorp(TFC3)",
    "UBLTFC5 - United Bank(TFC5)",
    "UMBLTFC1 - U Microfinance Bank Limited(TFC1)",
    "786 - 786 Investments Limited",
    "AABS - Al-Abbas Sugar Mills Limited",
    "AAL - Agro Allianz Limited",
    "AASM - Al-Abid Silk Mills Limited",
    "AATM - Ali Asghar Textile Mills Limited",
    "ABL - Allied Bank Limited",
    "ABOT - Abbott Laboratories (Pakistan) Limited",
    "ABSON - Abson Industries Limited",
    "ACIETF - Alfalah Consumer Index (ETF)",
    "ACPL - Attock Cement Pakistan Limited",
    "ADAMS - Adam Sugar Mills Limited",
    "ADMM - Artistic Denim Mills Limited",
    "ADOS - Ados Pakistan Limited",
    "ADTM - Adil Textile Mills Limited",
    "AEL - AEL Textile Limited",
    "AGHA - Agha Steel Ind.Ltd",
    "AGIC - Askari General Insurance Company Limited",
    "AGIL - Agriauto Industries Limited",
    "AGL - Agritech Limited",
    "AGLNCPS - Agritech Non-Voting (Pref) Class A",
    "AGP - AGP Limited",
    "AGSML - Abdullah Shah Ghazi Sugar Mills Limited",
    "AGTL - Al-Ghazi Tractors Limited",
    "AHCL - Arif Habib Corporation Limited",
    "AHL - Arif Habib Limited",
    "AHTM - Ahmad Hassan Textile Mills Limited",
    "AICL - Adamjee Insurance Company Limited",
    "AIRLINK - Air Link Communication Limited",
    "AKBL - Askari Bank Limited",
    "AKDCL - AKD Capital Limited",
    "AKDHL - AKD Hospitality Limited",
    "AKDSL - AKD Securities Limited",
    "AKGL - Al-Khair Gadoon Limited",
    "AKZO - Akzo Nobel Pakistan Limited",
    "ALAC - Askari Life Assurance Company Limited",
    "ALIFE - Adamjee Life Assurance Company Limited",
    "ALNRS - Al-Noor Sugar Mills Limited",
    "ALQT - Al-Qadir Textile Mills Limited",
    "ALTN - Altern Energy Limited",
    "AMBL - Apna Microfinance Bank Limited",
    "AMSL - Al-Mal Securities & Services Limited",
    "AMTEX - Amtex Limited",
    "ANL - Azgard Nine Limited",
    "ANLPS - Azgard Nine 8.95%(Pref)",
    "ANNT - Annoor Textile Mills Limited",
    "ANSM - Ansari Sugar Mills Limited",
    "ANTM - AN Textile Mills Limited",
    "APL - Attock Petroleum Limited",
    "APOT - Apollo Textile Mills Limited",
    "AQTM - Al-Qaim Textile Mills Limited",
    "ARCTM - Arctic Textile Mills Limited",
    "ARM - Allied Rental Modaraba",
    "ARPAK - Arpak International Investments Ltd.",
    "ARPL - Archroma Pakistan Limited",
    "ARUJ - Aruj Industries Limited",
    "ASC - Al Shaheer Corporation Limited",
    "ASCR1 - AL-Shaheer (R)",
    "ASHT - Ashfaq Textile Mills Limited",
    "ASIC - Asia Insurance Company Limited",
    "ASL - Aisha Steel Mills Limited",
    "ASLCPS - Aisha Steel Convt (Pref) Right",
    "ASLPS - Aisha Steel Convertible (Pref)",
    "ASRL - Associated Services Limited",
    "ASTL - Amreli Steels Limited",
    "ASTM - Asim Textile Mills Limited",
    "ATBA - Atlas Battery Limited",
    "ATIL - Atlas Insurance Limited",
    "ATLH - Atlas Honda Limited",
    "ATRL - Attock Refinery Limited",
    "AVN - Avanceon Limited",
    "AWTX - Allawasaya Tex. & Finishing Mills Ltd",
    "AWWAL - Awwal Modaraba",
    "AYTM - Ayesha Textile Mills Limited",
    "AYZT - Ayaz Textile Mills Limited",
    "AZMT - Azmat Textile Mills Limited",
    "AZTM - Al-Azhar Textile Mills Limited",
    "BAFL - Bank Alfalah Limited",
    "BAFS - Baba Farid Sugar Mills Limited",
    "BAHL - Bank AL Habib Limited",
    "BAPL - Bawany Air Products Limited",
    "BATA - Bata Pakistan Limited",
    "BBFL - Big Bird Foods Limited",
    "BCL - Bolan Castings Limited",
    "BCML - Babri Cotton Mills Limited",
    "BECO - Beco Steel Limited",
    "BEEM - Beema-Pakistan Company Limited",
    "BELA - Bela Automotives Limited",
    "BERG - Berger Paints Pakistan Limited",
    "BFBIO - BF Biosciences Limited",
    "BFMOD - B.F. Modaraba",
    "BGL - Baluchistan Glass Limited",
    "BHAT - Bhanero Textile Mills Limited",
    "BIFO - Biafo Industries Limited",
    "BIIC - Business & Industrial Insurance Company",
    "BILF - Bilal Fibres Limited",
    "BIPL - BankIslami Pakistan Limited",
    "BIPLS - BIPL Securities Limited",
    "BML - Bank Makramah Limited",
    "BNL - Bunnys Limited",
    "BNWM - Bannu Woollen Mills Limited",
    "BOK - The Bank of Khyber",
    "BOP - The Bank of Punjab",
    "BPBL - Balochistan Particle Board Limited",
    "BPL - Burshane LPG (Pakistan) Limited",
    "BROT - Brothers Textile Mills Limited",
    "BRR - B.R.R. Guardian Modaraba",
    "BRRG - B.R.R Guardian Limited",
    "BTL - Blessed Textiles Limited",
    "BUXL - Buxly Paints Limited",
    "BWCL - Bestway Cement Limited",
    "BWHL - Baluchistan Wheels Limited",
    "BYCO - Byco Petroleum Pakistan Limited",
    "CASH - Calcorp Limited",
    "CCM - Crescent Cotton Mills Limited",
    "CECL - Climax Engineering Company Limited",
    "CENI - Century Insurance Company Limited",
    "CEPB - Century Paper & Board Mills Limited",
    "CFL - Crescent Fibres Limited",
    "CHAS - Chashma Sugar Mills Limited",
    "CHBL - Chenab Limited",
    "CHCC - Cherat Cement Company Limited",
    "CJPL - Crescent Jute Products Limited",
    "CLCPS - Chenab Limited (Pref)",
    "CLOUD - Chakwal Spinning Mills Limited",
    "CLOV - Clover Pakistan Limited",
    "CLVL - Cordoba Logistics & Ventures Limited",
    "CNERGY - Cnergyico PK  Limited",
    "COLG - Colgate-Palmolive (Pakistan) Limited",
    "COST - (Colony) Sarhad Textile Mills Limited",
    "CPAL - Capital Assets Leasing Corporation",
    "CPHL - Citi Pharma Ltd.",
    "CPPL - Cherat Packaging Limited",
    "CRTM - The Crescent Textile Mills Limited",
    "CSAP - Crescent Steel & Allied Products Limited",
    "CSIL - Crescent Star Insurance Limited",
    "CSM - Cresent Standard Modaraba",
    "CTM - Colony Textile Mills Limited",
    "CWSM - Chakwal Spinning Mills Limited",
    "CYAN - Cyan Limited",
    "DAAG - Data Agro Limited",
    "DADX - Dadex Eternit Limited",
    "DATM - Data Textiles Limited",
    "DAWH - Dawood Hercules Corporation Limited",
    "DBCI - Dadabhoy Cement Industries Limited",
    "DBSL - Dadabhoy Sack Limited",
    "DCL - Dewan Cement Limited",
    "DCM - Dawood Capital Management Limited",
    "DCR - Dolmen City REIT",
    "DCTL - Dadabhoy Construction Technology Limited",
    "DEL - Dawood Equities Limited",
    "DFML - Dewan Farooque Motors Limited",
    "DFSM - Dewan Farooque Spinning Mills Limited",
    "DGKC - D.G. Khan Cement Company Limited",
    "DIIL - Diamond Industries Limited",
    "DINT - Din Textile Mills Limited",
    "DKL - Drekkar Kingsway Limited",
    "DKTM - Dewan Khalid Textile Mills Limited",
    "DLL - Dawood Lawrencepur Limited",
    "DMIL - D.M. Industries Limited",
    "DMTM - Dewan Mushtaq Textile Mills Limited",
    "DMTX - D.M. Textile Mills Limited",
    "DNCC - Dandot Cement Company Limited",
    "DOL - Descon Oxychem Limited",
    "DOLCPS - Descon Oxychem Limited (12%Non-Voting Pref)",
    "DOMF - Dominion Stock Fund Limited",
    "DSFL - Dewan Salman Fibre Limited",
    "DSIL - D.S. Industries Limited",
    "DSL - Dost Steels Limited",
    "DSML - Dar-es-Salaam Textile Mills Limited",
    "DWAE - Dewan Automotive Engineering Limited",
    "DWSM - Dewan Sugar Mills Limited",
    "DWTM - Dewan Textile Mills Limited",
    "DYNO - Dynea Pakistan Limited",
    "ECOP - Ecopack Limited",
    "EFERT - Engro Fertilizers Limited",
    "EFGH - EFG Hermes Pakistan Limited",
    "EFOODS - Engro Foods Limited",
    "EFUG - EFU General Insurance Limited",
    "EFUL - EFU Life Assurance Limited",
    "ELCM - Elahi Cotton Mills Limited",
    "ELSM - Ellcot Spinning Mills Limited",
    "EMCO - Emco Industries Limited",
    "ENGL - English Leasing Limited",
    "ENGRO - Engro Corporation Limited",
    "EPCL - Engro Polymer & Chemicals Limited",
    "EPCLPS - Engro Poly(Pref)",
    "EPQL - Engro Powergen Qadirpur Limited",
    "ESBL - Escorts Investment Bank Limited",
    "EWIC - East West Insurance Company Limited",
    "EWICR1 - East West (R)",
    "EWLA - East West Life Assurance Company Limited",
    "EXIDE - Exide Pakistan Limited",
    "EXTR - Extraction (Pakistan) Limited",
    "FABL - Faysal Bank Limited",
    "FAEL - Fatima Enterprises Limited",
    "FANM - First Al-Noor Modaraba",
    "FASM - Faisal Spinning Mills Limited",
    "FATIMA - Fatima Fertilizer Company Limited",
    "FCCL - Fauji Cement Company Limited",
    "FCEL - First Capital Equities Limited",
    "FCEPL - Frieslandcampina Engro Pakistan Limited",
    "FCIBL - First Credit and Investment Bank Limited",
    "FCL - Fast Cables Limited",
    "FCONM - First Constellation Modaraba",
    "FCSC - First Capital Securities Corporation",
    "FDIBL - First Dawood Investment Bank Limited",
    "FDMF - First Dawood Mutual Fund",
    "FDPL - First Dawood Properties Limited",
    "FECM - First Elite Capital Modaraba",
    "FECTC - Fecto Cement Limited",
    "FEM - First Equity Modaraba",
    "FEROZ - Ferozsons Laboratories Limited",
    "FFBL - Fauji Fertilizer Bin Qasim Limited",
    "FFC - Fauji Fertilizer Company Limited",
    "FFL - Fauji Foods Limited",
    "FFLM - First Fidelity Leasing Modaraba",
    "FFLR1 - Fauji Foods Ltd(R)",
    "FHAM - First Habib Modaraba",
    "FIBLM - First IBL Modaraba",
    "FIL - Fateh Industries Limited",
    "FIM - First Investec Modaraba",
    "FIMM - First Imrooz Modaraba",
    "FLYNG - Flying Cement Company Limited",
    "FLYNGR1 - Flying Cement(R)",
    "FML - Feroze1888 Mills Limited",
    "FNBM - First National Bank Modaraba",
    "FNEL - First National Equities Limited",
    "FPJM - First Punjab Modaraba",
    "FPRM - First Paramount Modaraba",
    "FRCL - Frontier Ceramics Limited",
    "FRSM - Faran Sugar Mills Limited",
    "FSWL - Fateh Sports Wear Limited",
    "FTHM - Fateh Textile Mills Limited",
    "FTMM - First Treet Manufacturing Modaraba",
    "FTSM - First Tri-Star Modaraba",
    "FUDLM - First UDL Modaraba",
    "FZCM - Fazal Cloth Mills Limited",
    "GADT - Gadoon Textile Mills Limited",
    "GAIL - Ghani Automobile Industries Limited",
    "GAL - Ghandhara Automobiles Limited",
    "GAMON - Gammon Pakistan Limited",
    "GASF - Golden Arrow Selected Stocks",
    "GATI - Gatron (Industries) Limited",
    "GATM - Gul Ahmed Textile Mills Limited",
    "GCIL - Ghani Chemical Industries Limited",
    "GCILB - Ghani Chemical Industries Limited (B)",
    "GEMBCEM - Burj Clean Energy Modaraba(GEM)",
    "GEMBLUEX - Blue-Ex Limited (GEM)",
    "GEMMEL - Mughal Energy Limited(GEM)",
    "GEMPAPL - Pak Agro Packaging Limited(GEM)",
    "GEMSPNL - Supernet Limited",
    "GEMUNSL - Universal Network Systems Limited(GEM)",
    "GENP - Genertech Pakistan Limited",
    "GFIL - Ghazi Fabrics International Limited",
    "GGGL - Ghani Global Glass Limited",
    "GGGLR1 - Ghani Global(R)",
    "GGL - Ghani Global Holdings Limited",
    "GGLR1 - Ghani Global(R)",
    "GHGL - Ghani Glass Limited",
    "GHNI - Ghandhara Industries Limited",
    "GHNL - Ghandhara Nissan Limited",
    "GIL - Good Luck Industries Ltd.",
    "GLAT - Glamour Textile Mills Limited",
    "GLAXO - GlaxoSmithKline Pakistan Limited",
    "GLOT - Globe Textile Mills Limited",
    "GLPL - Gillette Pakistan Limited",
    "GOC - GOC (Pak) Limited.",
    "GOEM - Globe Textile Mills (OE) Limited",
    "GRR - Globe Residency REIT",
    "GRYL - Grays Leasing Limited",
    "GSKCH - GlaxoSmithKline Consumer Healthcare",
    "GSPM - Gulshan Spinning Mills Limited",
    "GTECH - G3 Technologies Limited",
    "GTECHBR - G3 Technologies Ltd.CLASS B",
    "GTYR - Ghandhara Tyre & Rubber Company Limited",
    "GUSM - Gulistan Spinning Mills Limited",
    "GUTM - Gulistan Textile Mills Limited",
    "GVGL - Ghani Value Glass Limited",
    "GWLC - Gharibwal Cement Limited",
    "HABSM - Habib Sugar Mills Limited",
    "HACC - Hashimi Can Company Limited",
    "HADC - Haydari Construction Company Limited",
    "HAEL - Hala Enterprises Limited",
    "HAFL - Hafiz Limited",
    "HAJT - Hajra Textile Mills Limited",
    "HAL - Habib-ADM Limited",
    "HALEON - Haleon Pakistan Limited",
    "HASCOL - Hascol Petroleum Limited",
    "HASCOLR1 - Hascol Petre(R)",
    "HATM - Hamid Textile Mills Limited",
    "HBL - Habib Bank Limited",
    "HBLTETF - HBL Total Treasury (ETF)",
    "HCAR - Honda Atlas Cars (Pakistan) Limited",
    "HCL - Hallmark Company Limited",
    "HGFA - HBL Growth Fund",
    "HICL - Habib Insurance Company Limited",
    "HIFA - HBL Investment Fund",
    "HINO - Hinopak Motors Limited",
    "HINOON - Highnoon Laboratories Limited",
    "HIRAT - Hira Textile Mills Limited",
    "HKKT - Hakkim Textile Mills Limited",
    "HMB - Habib Metropolitan Bank Limited",
    "HMICL - Hallmark Insurance Company Limited",
    "HMIM - Haji Mohammad Ismail Mills Limited",
    "HMM - Habib Metro Mod",
    "HPL - Hoechst Pakistan Limited",
    "HRPL - Habib Rice Product Limited.",
    "HSM - Husein Sugar Mills Limited",
    "HSMCPS - Husein Sugar(Pref)",
    "HSMPSR - Husein Sugar(R)",
    "HSPI - Huffaz Seamless Pipe Industries Limited",
    "HTL - Hi-Tech Lubricants Limited",
    "HUBC - The Hub Power Company Limited",
    "HUMNL - Hum Network Limited",
    "HUSI - Husein Industries Limited",
    "HWQS - Haseeb Waqas Sugar Mills Limited",
    "IBFL - Ibrahim Fibres Limited",
    "IBLHL - IBL HealthCare Limited",
    "ICCI - ICC Industries Limited",
    "ICCT - ICC Textiles Limited",
    "ICI - ICI Pakistan Limited",
    "ICIBL - Invest Capital Investment Bank Limited",
    "ICL - Ittehad Chemicals Limted",
    "IDRT - Idrees Textile Mills Limited",
    "IDSM - Ideal Spinning Mills Limited",
    "IDYM - Indus Dyeing & Manufacturing Co. Limited",
    "IFSL - Invest & Finance Securities Limited",
    "IGIBL - IGI Investment Bank Limited",
    "IGIHL - IGI Holdings Limited",
    "IGIIL - IGI Insurance Limited",
    "IGIL - IGI Life Insurance Limited",
    "ILP - Interloop Limited",
    "ILTM - Island Textile Mills Limited",
    "IMAGE - Image Pakistan Limited",
    "IMAGER1 - Image Pak Ltd(R)",
    "IML - Imperial  Limited",
    "IMS - Intermarket Securities Limited",
    "IMSL - Imperial Sugar Limited",
    "INDU - Indus Motor Company Limited",
    "INIL - International Industries Limited",
    "INKL - International Knitwear Limited",
    "INMF - Investec Mutual Fund Limited",
    "IPAK - International Packaging Films Limited",
    "ISHT - Ishtiaq Textile Mills Limited",
    "ISIL - Ismail Industries Limited",
    "ISL - International Steels Limited",
    "ISTM - Ishaq Textile Mills Limited",
    "ITSL - Investec Securities Limited",
    "ITTEFAQ - Ittefaq Iron Industries Limited",
    "JATM - J.A. Textile Mills Limited",
    "JDMT - Janana De Malucho Textile Mills Limited",
    "JDWS - JDW Sugar Mills Limited",
    "JGICL - Jubilee General Insurance Limited",
    "JKSM - J.K. Spinning Mills Limited",
    "JLICL - Jubilee Life Insurance Company Limited",
    "JOPP - Johnson & Phillips (Pakistan) Limited",
    "JOVC - Javed Omer Vohra & Company Limited",
    "JPGL - Japan Power Generation Limited",
    "JSBL - JS Bank Limited",
    "JSBLR1 - JS Bank Limited Right (R)",
    "JSCL - Jahangir Siddiqui & Co. Ltd.",
    "JSCLPSA - Jahangir Sidd(Pref)",
    "JSCLR1 - Jahangi Sidd(R)",
    "JSGBETF - JS Global Banking Sector(ETF)",
    "JSGCL - JS Global Capital Limited",
    "JSIL - JS Investments Limited",
    "JSMFETF - JS Momentum Factor Exchange Traded Fund",
    "JSML - Jauharabad Sugar Mills Limited",
    "JUBS - Jubilee Spinning & Weaving Mills Ltd.",
    "JVDC - Javedan Corporation Limited",
    "JVDCPS - Javedan Corporation (Pref)",
    "KACM - Karim Cotton Mills Limited",
    "KAKL - Kaiser Arts & Krafts Limited",
    "KAPCO - Kot Addu Power Company Limited",
    "KASBM - KASB Modaraba",
    "KCL - Karam Ceramics Limited",
    "KEL - K-Electric Limited",
    "KHSM - Khurshid Spinning Mills Limited",
    "KHTC - Khyber Tobacco Company Limited",
    "KHYT - Khyber Textile Mills Limited",
    "KML - Kohinoor Mills Limited",
    "KOHC - Kohat Cement Company Limited",
    "KOHE - Kohinoor Energy Limited",
    "KOHP - Kohinoor Power Company Limited",
    "KOHTM - Kohat Textile Mills Limited",
    "KOIL - Kohinoor Industries Limited",
    "KOSM - Kohinoor Spinning Mills Limited",
    "KPUS - Khairpur Sugar Mills Limited",
    "KSBP - KSB Pumps Company Limited",
    "KSTM - Khalid Siraj Textile Mills Limited",
    "KTML - Kohinoor Textile Mills Limited",
    "LCI - Lucky Core Industries Limited",
    "LEUL - Leather Up Limited",
    "LINDE - Linde Pakistan Limited",
    "LIVEN - Liven Pharma Limited",
    "LMSM - Landmark Spinning Industries Limited",
    "LOADS - Loads Limited",
    "LOTCHEM - Lotte Chemical Pakistan Limited",
    "LPCL - Lafarge Pakistan Cement Limited",
    "LPGL - Leiner Pak Gelatine Limited",
    "LPL - Lalpir Power Limited",
    "LSECL - LSE Capital Limited.",
    "LSEFSL - LSE Financial Services Limited.",
    "LSEPL - LSE Proptech Limited",
    "LSEVL - LSE Ventures Limited",
    "LUCK - Lucky Cement Limited",
    "MACFL - MACPAC Films Limited",
    "MACTER - Macter International Limited",
    "MARI - Mari Energies Limited",
    "MCB - MCB Bank Limited",
    "MCBAH - MCB-Arif Habib Savings and Invest",
    "MCBIM - MCB Investment Management Limited.",
    "MDTL - Media Times Limited",
    "MDTM - Mehr Dastgir Textile Mills Limited",
    "MEBL - Meezan Bank Limited",
    "MEHT - Mehmood Textile Mills Limited",
    "MERIT - Merit Packaging Limited",
    "META - MetaTech Trading Limited",
    "MFFL - Mitchells Fruit Farms Limited",
    "MFL - Matco Foods Limited",
    "MFTM - Mohammad Farooq Textile Mills Limited",
    "MIIETF - Mahaana Islamic Index ETF",
    "MIRKS - Mirpurkhas Sugar Mills Limited",
    "MLCF - Maple Leaf Cement Factory Limited",
    "MLCFR1 - Maple Leaf (R)",
    "MODAM - Modaraba Al-Mali",
    "MODAMR1 - MODARABA AL-MALI (R)",
    "MOHE - Mohib Exports Limited",
    "MOIL - Morafco Industries Limited",
    "MOON - Moonlite (Pak) Limited",
    "MQTM - Maqbool Textile Mills Limited",
    "MRNS - Mehran Sugar Mills Limited",
    "MSCL - Metropolitan Steel Corporation Limited",
    "MSOT - Masood Textile Mills Limited",
    "MSOTPS - Masood Textile (Pref)",
    "MTIL - Mian Textile Industries Limited",
    "MTL - Millat Tractors Limited",
    "MUBT - Mubarak Textile Mills Limited",
    "MUGHAL - Mughal Iron & Steel Industries Limited",
    "MUGHALR1 - Mughal Iron (R)",
    "MUKT - Mukhtar Textile Mills Limited",
    "MUREB - Murree Brewery Company Limited",
    "MWMP - Mandviwala Mauser Plastic Industries",
    "MZNPETF - Meezan Pakistan ETF",
    "MZSM - Mirza Sugar Mills Limited",
    "NAFL - National Fibres Limited",
    "NAGC - Nagina Cotton Mills Limited",
    "NATF - National Foods Limited",
    "NATM - Nadeem Textile Mills Limited",
    "NBP - National Bank of Pakistan",
    "NBPGETF - NBP Pakistan  Growth ETF",
    "NCL - Nishat Chunian Limited",
    "NCML - Nazir Cotton Mills Limited",
    "NCPL - Nishat Chunian Power Limited",
    "NESTLE - Nestle Pakistan Limited",
    "NETSOL - NetSol Technologies Limited",
    "NEXT - Next Capital Limited",
    "NIB - NIB Bank Limited",
    "NICL - Nimir Industrial Chemicals Limited",
    "NINA - Nina Industries Limited",
    "NITGETF - NIT Pakistan Gateway ETF",
    "NMFL - Nirala MSR Foods Limited",
    "NML - Nishat Mills Limited",
    "NONS - Noon Sugar Mills Limited",
    "NORS - Noor Silk Mills Limited",
    "NPL - Nishat Power Limited",
    "NPSM - N. P. Spinning Mills Limited",
    "NRL - National Refinery Limited",
    "NRSL - Nimir Resins Limited",
    "NSRM - The National Silk & Rayon Mills Limited",
    "OBOY - Oilboy Energy Limited",
    "OBOYR1 - Oilboy Energy(R)",
    "OCTOPUS - Octopus Digital Limited",
    "OGDC - Oil & Gas Development Company Limited",
    "OLPL - OLP Financial Services Pakistan Limited",
    "OLPM - OLP Modaraba",
    "OLSM - Olympia Spinning and Weaving Mills Limited",
    "OML - Olympia Mills Limited",
    "ORIXM - Orix Modaraba",
    "ORM - Orient Rental Mod",
    "OTSU - Otsuka Pakistan Limited",
    "PABC - Pakistan Aluminium Beverage Cans Limited",
    "PACE - Pace (Pakistan) Limited",
    "PAEL - Pak Elektron Limited",
    "PAKCEM - Pakcem Limited",
    "PAKD - Pak Datacom Limited",
    "PAKL - Pak Leather Crafts Limited",
    "PAKMI - First Pak Modaraba",
    "PAKOXY - Pakistan Oxygen Limited",
    "PAKRI - Pakistan Reinsurance Company Limited",
    "PAKT - Pakistan Tobacco Company Limited",
    "PASL - Pervez Ahmed Consultancy Services Ltd.",
    "PASM - Paramount Spinning Mills Limited",
    "PCAL - Pakistan Cables Limited",
    "PCML - Punjab Cotton Mill",
    "PDGH - Prudential Discourt & Guarantee House Lt",
    "PECO - Pakistan Engineering Company Limited",
    "PELPS - Pak Elektron (Pref)",
    "PGCL - Pakistan Gum & Chemicals Limited",
    "PGF - PICIC Growth Fund",
    "PGIC - Pakistan Guarantee Insurance Company Limited",
    "PGLC - Pak-Gulf Leasing Company Limited",
    "PHDL - Pakistan Hotels Developers Limited",
    "PIAA - Pakistan International Airlines Corp",
    "PIAB - Pakistan International Airlines Corporat",
    "PIAHCLA - PIA Holding Company Limited",
    "PIAHCLB - PIA Holding Company LimitedB",
    "PIBTL - Pakistan International Bulk Terminal",
    "PICL - Pakistan Industrial & Commercial Leasing",
    "PICT - Pakistan International Container",
    "PIF - PICIC Investment Fund",
    "PIL - PICIC Insurance Limited",
    "PIM - Popular Islamic Modaraba",
    "PINL - Premier Insurance Limited",
    "PIOC - Pioneer Cement Limited",
    "PKGI - The Pakistan General Insurance Co. Ltd.",
    "PKGP - Pakgen Power Limited",
    "PKGS - Packages Limited",
    "PMI - First Prudential Modaraba",
    "PMPK - Philip Morris (Pakistan) Limited",
    "PMRS - The Premier Sugar Mills",
    "PNGRS - Pangrio Sugar Mills Limited",
    "PNSC - Pakistan National Shipping Corporation",
    "POL - Pakistan Oilfields Limited",
    "POML - Punjab Oil Mills Limited",
    "POWER - Power Cement Limited",
    "POWERPS - Power Cement (Pref)",
    "POWERR1 - Power Cement (R)",
    "PPL - Pakistan Petroleum Limited",
    "PPP - Pakistan Paper Products Limited",
    "PPVC - Pakistan PVC Limited",
    "PREMA - At-Tahur Limited",
    "PRET - Premium Textile Mills Limited",
    "PRIB - Prudential Investment Bank Limited",
    "PRIC - Progressive Insurance Company Limited",
    "PRL - Pakistan Refinery Limited",
    "PRLR1 - Pak Refinery (R)",
    "PRWM - Prosperity Weaving Mills Limited",
    "PSEL - Pakistan Services Limited",
    "PSMC - Pak Suzuki Motor Company Limited",
    "PSO - Pakistan State Oil Company Limited",
    "PSX - Pakistan Stock Exchange Limited",
    "PSYL - Pakistan Synthetics Limited",
    "PTC - Pakistan Telecommunication Company Ltd",
    "PTL - Panther Tyres Ltd.",
    "PUDF - Prudential Stocks Fund Limited",
    "QUET - Quetta Textile Mills Limited",
    "QUICE - Quice Food Industries Limited",
    "QUSW - Quality Steel Works Limited",
    "RAVT - Ravi Textile Mills Limited",
    "RCML - Reliance Cotton Spinning Mills Limited",
    "REDCO - Redco Textiles Limited",
    "REGAL - Regal Ceramics Limited",
    "REWM - Reliance Weaving Mills Limited",
    "RICL - Reliance Insurance Company Limited",
    "RMPL - Rafhan Maize Products Company Limited",
    "RPL - Roshan Packages Limited",
    "RUBY - Ruby Textile Mills Limited",
    "RUPL - Rupali Polyester Limited",
    "SAIF - Saif Textile Mills Limited",
    "SALT - Salfi Textile Mills Limited",
    "SANE - Salman Noman Enterprises Limited",
    "SANSM - Sanghar Sugar Mills Limited",
    "SAPL - Sanofi-Aventis Pakistan Limited",
    "SAPT - Sapphire Textile Mills Limited",
    "SARC - Sardar Chemical Industries Limited",
    "SASML - Sindh Abadgars Sugar Mills Limited",
    "SAZEW - Sazgar Engineering Works Limited",
    "SBL - Samba Bank Limited",
    "SCBPL - Standard Chartered Bank (Pak) Ltd",
    "SCHT - Schon Textiles Limited",
    "SCL - Shield Corporation Limited",
    "SDIL - Saleem Denim Industries Limited",
    "SDOT - Sadoon Textile Industries Limited",
    "SEARL - The Searle Company Limited",
    "SEARLR1 - Searl Company(R)",
    "SEL - Sitara Energy Limited",
    "SEPCO - Southern Electric Power Company Limited",
    "SEPL - Security Papers Limited",
    "SERF - Service Fabrics Limited",
    "SERT - Service Industries Textiles Limited",
    "SFAT - Safa Textiles Limited",
    "SFL - Sapphire Fibres Limited",
    "SFLL - SFL Limited",
    "SGABL - SG.Allied Businesses Limited",
    "SGF - Service GlobalFootwear Limited",
    "SGFL - S.G.Fiber Limited",
    "SGPL - S.G. Power Limited",
    "SHCI - Shaffi Chemical Industries Limited",
    "SHCM - Shadman Cotton Mills Limited",
    "SHDT - Shadab Textile Mills Limited",
    "SHEL - Shell Pakistan Limited",
    "SHEZ - Shezan International Limited",
    "SHFA - Shifa International Hospitals Limited",
    "SHJS - Shahtaj Sugar Mills Limited",
    "SHNI - Shaheen Insurance Company Limited",
    "SHSML - Shahmurad Sugar Mills Limited",
    "SIBL - Security Investment Bank Limited",
    "SICL - Standard Insurance Company Limited",
    "SIEM - Siemens (Pakistan) Engineering",
    "SILK - Silkbank Limited",
    "SINDM - Sindh Modaraba",
    "SING - Singer Pakistan ",
    "SITC - Sitara Chemical Industries Limited",
    "SJTM - Sajjad Textile Mills Limited",
    "SKRS - Sakrand Sugar Mills Limited",
    "SLCL - Security Leasing Corporation Limited",
    "SLCPA - Security Leasing Corp.9.10%(Pref)",
    "SLGL - Secure Logistics Group Limited",
    "SLL - SME Leasing Limited",
    "SLSO - Saleem Sugar Mills Limited",
    "SLYT - Sally Textile Mills Limited",
    "SMBL - Summit Bank Limited",
    "SMBLCPSA - Summit Bank",
    "SMBLCPSB - Summit Bank B",
    "SMCPL - Safe Mix Concrete Limited",
    "SML - Shakarganj Limited",
    "SMTM - Samin Textiles Limited",
    "SNAI - Sana Industries Limited",
    "SNBL - Soneri Bank Limited",
    "SNGP - Sui Northern Gas Pipelines Limited",
    "SPEL - Synthetic Products Enterprises Limited",
    "SPL - Sitara Peroxide Limited",
    "SPLC - Saudi Pak Leasing Company Limited",
    "SPWL - Saif Power Limited",
    "SRSM - Sargodha Spinning Mills Limited",
    "SRVI - Service Industries Limited",
    "SSGC - Sui Southern Gas Company Limited",
    "SSIC - Silver Star Insurance Company Limited",
    "SSML - Saritow Spinning Mills Limited",
    "SSOM - S.S.Oil Mills Limited",
    "STCL - Shabbir Tiles & Ceramics Limited",
    "STJT - Shahtaj Textile Limited",
    "STML - Shams Textile Mills Limited",
    "STPL - Siddiqsons Tin Plate Limited",
    "STYLERS - Stylers International Limited",
    "SUCM - Sunshine Cotton Mills Limited",
    "SUHJ - Suhail Jute Mills Limited",
    "SURAJ - Suraj Ghee Industries Limited",
    "SURC - Suraj Cotton Mills Limited",
    "SUTM - Sunrays Textile Mills Limited",
    "SYM - Symmetry Group Limited",
    "SYS - Systems Limited",
    "SZTM - Shahzad Textile Mills Limited",
    "TAJT - Taj Textile Mills Limited",
    "TATM - Tata Textile Mills Limited",
    "TBL - Treet Battery Limited.",
    "TCLTC - Treet Corporation (Ptc)",
    "TCORP - Tariq Corporation Limited",
    "TCORPCPS - Tariq Corporation Limited(Pref)",
    "TCORPR1 - Tariq Corporation (Pvt) Ltd (R)",
    "TDIL - TPL Direct Insurance Limited",
    "TELE - Telecard Limited",
    "TGL - Tariq Glass Industries Limited",
    "THALL - Thal Limited",
    "THAS - Taha Spinning Mills Limited",
    "THCCL - Thatta Cement Company Limited",
    "TICL - The Thal Industries Corporation Limited",
    "TOMCL - The Organic Meat Company Limited",
    "TOWL - Towellers Limited",
    "TPL - TPL Corp Limited",
    "TPLI - TPL Insurance Limited",
    "TPLL - TPL Life Insurance Limited",
    "TPLP - TPL Properties Limited",
    "TPLRF1 - TPL REIT Fund I",
    "TPLT - TPL Trakker Limited",
    "TREET - Treet Corporation Limited",
    "TREI - Transmission Engineering Industries Limited",
    "TRG - TRG Pakistan Limited",
    "TRIBL - Trust Investment Bank Limited",
    "TRIPF - Tri-Pack Films Limited",
    "TRPOL - Tri-Star Polyester Limited",
    "TRSM - Trust Modaraba",
    "TSBL - Trust Securities & Brokerage Limited",
    "TSMF - Tri-Star Mutual Fund Limited",
    "TSML - Tandlianwala Sugar Mills Limited",
    "TSPL - Tri-Star Power Limited",
    "UBDL - United Brands Limited",
    "UBL - United Bank Limited",
    "UBLPETF - UBLPakistan Enterprise ETF",
    "UCAPM - Unicap Modaraba",
    "UDLI - UDL International Limited",
    "UDPL - United Distributors Pakistan Limited",
    "UNIC - The United Insurance Company",
    "UNITY - Unity Foods Limited",
    "UNITYR1 - Unity Foods(R)",
    "UPFL - Unilever Pakistan Foods Limited",
    "USMT - Usman Textile Mills Limited",
    "UVIC - The Universal Insurance Company Limited",
    "WAHN - Wah Noble Chemicals Limited",
    "WAVES - Waves Corporation Limited",
    "WAVESAPP - Waves Home Appliances Limited",
    "WAVESR1 - Waves Singer Pakistan Limited (R)",
    "WHALE - Waves Home Appliances Limited",
    "WTL - Worldcall Telecom Limited",
    "WYETH - Wyeth Pakistan Limited",
    "YOUW - Yousaf Weaving Mills Limited",
    "ZAHID - Zahidjee Textile Mills Limited",
    "ZELP - Zeal Pak Cement Factory Limited",
    "ZHCM - Zahur Cotton Mills Limited",
    "ZIL - ZIL Limited",
    "ZTL - Zephyr Textiles Limited"
  ]

# Extract just the symbols (everything before the " - ")
symbols = [entry.split(" - ")[0] for entry in companies]

# Print or use the cleaned list
print(symbols)